---
version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DEBUG: ${DEBUG:-1}
      DOCKER_HOST: unix:///var/run/docker.sock
      LS_LOG: WARN
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ".:/home/app"
    ports:
      - 5001:5001
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-2
    depends_on:
      - localstack
